package com.huizekb.bierlijst.bierlijst.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@DynamoDBTable(tableName = "houseMembers")
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Member {

    @DynamoDBHashKey(attributeName = "memberID")
    @DynamoDBAutoGeneratedKey
    private String memberID;

    @DynamoDBAttribute
    private String memberName;

    @DynamoDBAttribute
    private String memberLastname;

    @DynamoDBAttribute
    private Integer memberRemainingBeer;
}


